### Usher ticket
POST https://localhost:7229/organizer/event/usher-ticket
Content-Type: application/json
Authorization: bob

{
  "contractAddress": "0x415c9e5c9360da7a6477fd19fa3327032446645a",
  "ticketId": 0,
  "checkInSecret": "80a9bebd-a179-4a71-a276-a4687ef201c1"
}
