### Check in a ticket
POST http://localhost:5021//organizer/event/usher-ticket
Content-Type: application/json
Authorization: 0

{
  "contractId": 0,
  "ticketId": 0,
  "checkInSecret": "2b6385d5-8168-4304-955c-3c07f9b1f523"
}
